#!/bin/bash

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" -d "$POSTGRES_DB"  <<-EOSQL
  CREATE USER $TEST_APP_USER WITH PASSWORD '$TEST_APP_PASSWORD';
	CREATE DATABASE $TEST_APP_DB;
	GRANT ALL PRIVILEGES ON DATABASE $TEST_APP_DB TO $TEST_APP_USER;
EOSQL

psql -U "$TEST_APP_USER" -d "$TEST_APP_DB" -a -f /sql/001-init_tables.sql